# Generated by Django 3.1.1 on 2020-09-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20200911_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
